### ISSUE TITLE
Docs guides mention localhost instead of 0.0.0.0

### ISSUE THREAD

**Issue by clacladev** [ceramicstudio/js-composedb#109] opened 2023-03-03 10:32 UTC
# Description
In the docs, the guide I am following [create-your-composite](https://composedb.js.org/docs/0.4.x/create-your-composite) mentions multiple times to pass `localhost:7007` but on my macOS machine, it throws an error. As soon as I replace it with `0.0.0.0:7007` it works.

The error is:
```
✖ request to http://localhost:7007/api/v0/streams/kjzl6hvfrbw6c5ajfmes842lu09vjxu5956e3xq0xk12gp2jcf9s90cagt2god9?sync=0 failed, reason: connect ECONNREFUSED ::1:7007
```

I see throughout the docs that `localhost:7007` is widely mentioned. It would be worth to understand why on macOS it does not work and if it's the case to replace it docs wide with `0.0.0.0:7007`.

**Comment by m0ar** [comment] 2023-09-08 09:43
The reverse is true for linux machines, so simply swapping it just moves the problem :)

**Comment by dav1do** [comment] 2024-03-12 00:14
Thanks for the report! This error is commonly caused by using node v18 instead of v20 and we have a section on our [FAQ](https://developers.ceramic.network/docs/composedb/set-up-your-environment#3-frequently-asked-questions) about it now, so I'm going to close this issue. 

I think localhost is still the "correct" value for us to list in our docs but there are plenty of reasons it might not work in addition to using an unsupported node version. `localhost` is a special hostname that is the "loopback address" and typically points to the IP addresses 127.0.0.1 and ::1, which is where ceramic should be available since we're running the server on the same machine. You could set up custom DNS or `/etc/hosts` config to make localhost resolve to some other addresses if you know what you're doing - or just want to have a bad time. 

The IP address 0.0.0.0 also has a special meaning and _connecting_ to it is undefined afaik. As a server, binding to 0.0.0.0 means you want to listen on all addresses (and network interfaces). Connecting to it as a client is left as an exercise to the OS and might be an error, or might go to localhost, or might do something totally unexpected! Here's a [SO post](https://unix.stackexchange.com/a/419881) with links to the RFCs if you're curious for more details.

**Closed by dav1do** 2024-03-12 00:14 UTC
